import type { ProfileActionReport, ProfileInfo, ProfileReport } from "./types";

const mockProfiles: ProfileInfo[] = [
  {
    name: "codex",
    alias: "Default",
    category: "默认",
    note: null,
    codexHome: "/Users/ikiru/.codex",
    userDataDir: "/Users/ikiru/Library/Application Support/Codex",
    configPath: "/Users/ikiru/.codex/config.toml",
    model: "gpt-5.5",
    reasoningEffort: "medium",
    homeExists: true,
    userDataExists: true,
    configExists: true,
    websocketFeaturesEnabled: true,
    managedByApp: false,
    isDefault: true,
    zshrcLine: 0,
    isRunning: false,
    runningPids: [],
    runningProcessCount: 0,
    account: null,
    latestSession: {
      id: "019e86f9-09aa-73b0-989a-fe792db41e7a",
      title: "优惠券配置优化",
      summary: "梳理优惠券配置表单、校验规则和发布流程的交互细节。",
      updatedAt: "2026-06-02T06:17:04.571447Z",
      startedAt: "2026-06-02T05:52:11.231Z",
      cwd: "/Users/ikiru/Documents/r-series-public",
      path: "/Users/ikiru/.codex/sessions/2026/06/02/rollout-2026-06-02T13-52-11-019e86f9-09aa-73b0-989a-fe792db41e7a.jsonl",
    },
  },
  {
    name: "codex-b",
    alias: "Balance",
    category: "平衡",
    note: "日常修改和常规编码。",
    codexHome: "/Users/ikiru/.codex-isolated-test",
    userDataDir: "/Users/ikiru/Library/Application Support/Codex-Isolated-Test",
    configPath: "/Users/ikiru/.codex-isolated-test/config.toml",
    model: "gpt-5.5",
    reasoningEffort: "medium",
    homeExists: true,
    userDataExists: true,
    configExists: true,
    websocketFeaturesEnabled: false,
    managedByApp: false,
    isDefault: false,
    zshrcLine: 23,
    isRunning: true,
    runningPids: [3831],
    runningProcessCount: 1,
    account: {
      authMode: "chatgpt",
      email: "demo@example.com",
      name: "Demo",
      accountId: "acct_demo",
      userId: "user_demo",
      planType: "plus",
      organizationTitle: "Personal",
      lastRefresh: new Date().toISOString(),
    },
    latestSession: {
      id: "019e8b38-c4f3-7281-8b15-acc716cd7a3f",
      title: "优化 Codex Manage",
      summary: "能展示最新的会话摘要标题、摘要信息吗;",
      updatedAt: "2026-06-03T02:47:55.000000Z",
      startedAt: "2026-06-03T02:03:34.047Z",
      cwd: "/Users/ikiru/Documents/r-series-public",
      path: "/Users/ikiru/.codex-isolated-test/sessions/2026/06/03/rollout-2026-06-03T10-03-34-019e8b38-c4f3-7281-8b15-acc716cd7a3f.jsonl",
    },
  },
  {
    name: "codex-e",
    alias: "Deep Draft",
    category: "深度",
    note: "复杂设计和长任务。",
    codexHome: "/Users/ikiru/.codex-e",
    userDataDir: "/Users/ikiru/Library/Application Support/Codex-E",
    configPath: "/Users/ikiru/.codex-e/config.toml",
    model: "gpt-5.5",
    reasoningEffort: "xhigh",
    homeExists: true,
    userDataExists: true,
    configExists: true,
    websocketFeaturesEnabled: true,
    managedByApp: true,
    isDefault: false,
    zshrcLine: 44,
    isRunning: false,
    runningPids: [],
    runningProcessCount: 0,
    account: null,
    latestSession: null,
  },
];

export function createMockProfileReport(): ProfileReport {
  return {
    generatedAt: new Date().toISOString(),
    zshrcPath: "/Users/ikiru/.zshrc",
    metadataPath: "/Users/ikiru/.rcodexmanager/profile-metadata.json",
    homeDir: "/Users/ikiru",
    profileCount: mockProfiles.length,
    profiles: mockProfiles,
  };
}

export function createMockActionReport(action: string, name: string): ProfileActionReport {
  return {
    generatedAt: new Date().toISOString(),
    action,
    zshrcPath: "/Users/ikiru/.zshrc",
    profile: mockProfiles.find((profile) => profile.name === name) ?? null,
    backups: [],
    message: `${action} ${name}`,
  };
}
