import type { ProfileActionReport, ProfileInfo, ProfileReport } from "./types";

const mockProfiles: ProfileInfo[] = [
  {
    name: "codex",
    alias: "Default",
    category: "默认",
    note: null,
    codexHome: "/Users/ikiru/.codex",
    userDataDir: "/Users/ikiru/Library/Application Support/Codex",
    configPath: "/Users/ikiru/.codex/config.toml",
    model: "gpt-5.5",
    reasoningEffort: "medium",
    homeExists: true,
    userDataExists: true,
    configExists: true,
    websocketFeaturesEnabled: true,
    managedByApp: false,
    isDefault: true,
    zshrcLine: 0,
    isRunning: false,
    runningPids: [],
    runningProcessCount: 0,
    account: null,
  },
  {
    name: "codex-b",
    alias: "Balance",
    category: "平衡",
    note: "日常修改和常规编码。",
    codexHome: "/Users/ikiru/.codex-isolated-test",
    userDataDir: "/Users/ikiru/Library/Application Support/Codex-Isolated-Test",
    configPath: "/Users/ikiru/.codex-isolated-test/config.toml",
    model: "gpt-5.5",
    reasoningEffort: "medium",
    homeExists: true,
    userDataExists: true,
    configExists: true,
    websocketFeaturesEnabled: false,
    managedByApp: false,
    isDefault: false,
    zshrcLine: 23,
    isRunning: true,
    runningPids: [3831],
    runningProcessCount: 1,
    account: {
      authMode: "chatgpt",
      email: "demo@example.com",
      name: "Demo",
      accountId: "acct_demo",
      userId: "user_demo",
      planType: "plus",
      organizationTitle: "Personal",
      lastRefresh: new Date().toISOString(),
    },
  },
  {
    name: "codex-e",
    alias: "Deep Draft",
    category: "深度",
    note: "复杂设计和长任务。",
    codexHome: "/Users/ikiru/.codex-e",
    userDataDir: "/Users/ikiru/Library/Application Support/Codex-E",
    configPath: "/Users/ikiru/.codex-e/config.toml",
    model: "gpt-5.5",
    reasoningEffort: "xhigh",
    homeExists: true,
    userDataExists: true,
    configExists: true,
    websocketFeaturesEnabled: true,
    managedByApp: true,
    isDefault: false,
    zshrcLine: 44,
    isRunning: false,
    runningPids: [],
    runningProcessCount: 0,
    account: null,
  },
];

export function createMockProfileReport(): ProfileReport {
  return {
    generatedAt: new Date().toISOString(),
    zshrcPath: "/Users/ikiru/.zshrc",
    metadataPath: "/Users/ikiru/.rcodexmanager/profile-metadata.json",
    homeDir: "/Users/ikiru",
    profileCount: mockProfiles.length,
    profiles: mockProfiles,
  };
}

export function createMockActionReport(action: string, name: string): ProfileActionReport {
  return {
    generatedAt: new Date().toISOString(),
    action,
    zshrcPath: "/Users/ikiru/.zshrc",
    profile: mockProfiles.find((profile) => profile.name === name) ?? null,
    backups: [],
    message: `${action} ${name}`,
  };
}
